
package music_player;

import java.awt.Color;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import javax.swing.*;
import javazoom.jl.player.Player;

/**
 *
 * @author lenovo
 */
public class MusicFrame extends javax.swing.JFrame {

    /**
     * Creates new form MusicFrame
     */
    long total_length=0,pouse=0;
   static int flag=0,fl=0,f=1,fp=1,i=-1,count=0;
   static String st,name,song,path=null;
    FileInputStream FIS;
    BufferedInputStream BIS;
    Player player;
    static boolean b=false,c=true;
   static File myfile=null,lastDirectory=null,fil[];
    JFileChooser ch;
    public MusicFrame() {
        initComponents();
        sname.setText("Select an mp3 file!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        r2 = new javax.swing.JRadioButton();
        r1 = new javax.swing.JRadioButton();
        next = new javax.swing.JButton();
        Mlist = new javax.swing.JButton();
        pause = new javax.swing.JButton();
        playb = new javax.swing.JButton();
        prev = new javax.swing.JButton();
        sname = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jmusic_Player\n");
        setLocation(new java.awt.Point(350, 205));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("About");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 153), new java.awt.Color(0, 51, 153), new java.awt.Color(153, 153, 255), new java.awt.Color(153, 153, 255)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("playing :-");

        r2.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        r2.setForeground(new java.awt.Color(0, 102, 102));
        r2.setSelected(true);
        r2.setText("auto");
        r2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 153), new java.awt.Color(0, 51, 153), new java.awt.Color(153, 153, 255), new java.awt.Color(153, 153, 255)));
        r2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                r2MouseReleased(evt);
            }
        });

        r1.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        r1.setForeground(new java.awt.Color(0, 102, 102));
        r1.setText("loop");
        r1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 153), new java.awt.Color(0, 51, 153), new java.awt.Color(153, 153, 255), new java.awt.Color(153, 153, 255)));
        r1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                r1MouseReleased(evt);
            }
        });
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });

        next.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        next.setForeground(new java.awt.Color(0, 102, 102));
        next.setText("next");
        next.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 153), new java.awt.Color(0, 51, 153), new java.awt.Color(153, 153, 255), new java.awt.Color(153, 153, 255)));
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nextMouseReleased(evt);
            }
        });

        Mlist.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        Mlist.setForeground(new java.awt.Color(0, 102, 102));
        Mlist.setText("List");
        Mlist.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 153), new java.awt.Color(0, 51, 153), new java.awt.Color(153, 153, 255), new java.awt.Color(153, 153, 255)));
        Mlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MlistMouseReleased(evt);
            }
        });
        Mlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MlistActionPerformed(evt);
            }
        });

        pause.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        pause.setForeground(new java.awt.Color(0, 102, 102));
        pause.setText("pause");
        pause.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 153), new java.awt.Color(0, 51, 153), new java.awt.Color(153, 153, 255), new java.awt.Color(153, 153, 255)));
        pause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pauseMouseReleased(evt);
            }
        });
        pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });

        playb.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        playb.setForeground(new java.awt.Color(0, 102, 102));
        playb.setText("play");
        playb.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 153), new java.awt.Color(0, 0, 153), new java.awt.Color(153, 153, 255), new java.awt.Color(153, 153, 255)));
        playb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                playbMouseReleased(evt);
            }
        });
        playb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playbActionPerformed(evt);
            }
        });

        prev.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        prev.setForeground(new java.awt.Color(0, 102, 102));
        prev.setText("prev");
        prev.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 153), new java.awt.Color(0, 51, 153), new java.awt.Color(153, 153, 255), new java.awt.Color(153, 153, 255)));
        prev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                prevMouseReleased(evt);
            }
        });

        sname.setBackground(new java.awt.Color(204, 255, 204));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/music_player/g4.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(prev, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(playb, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pause, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(Mlist, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(r1)
                                    .addComponent(r2))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Mlist, next, pause, playb, prev});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(r1)
                        .addGap(18, 18, 18)
                        .addComponent(r2)
                        .addGap(58, 58, 58)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prev)
                    .addComponent(playb)
                    .addComponent(pause, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(next)
                    .addComponent(Mlist))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Mlist, next, pause, playb, prev});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playbMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playbMouseReleased
          pause.setBackground(Color.lightGray);
          playb.setBackground(Color.BLUE);
          if(fp==0){
          fl=1;
          fp=1;
          Play(song);
          }
    }//GEN-LAST:event_playbMouseReleased

    private void playbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playbActionPerformed

    private void pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pauseActionPerformed

    private void pauseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pauseMouseReleased
        // TODO add your handling code here:
        playb.setBackground(Color.LIGHT_GRAY);
        pause.setBackground(Color.BLUE);
        if(player!=null)
        {
            try
            {
                pouse=FIS.available();
                player.close();
                fp=0;
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_pauseMouseReleased

    private void MlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MlistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MlistActionPerformed

    private void MlistMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MlistMouseReleased
        // TODO add your handling code here:
        try {     
            count=0;
                ch = new JFileChooser(path);
                int val=ch.showOpenDialog(null);
                if(val==JFileChooser.APPROVE_OPTION)
                {
                   if(flag>0)
                   {
                       player.close();
                   }
                  path=ch.getSelectedFile().getPath();
                    myfile=ch.getSelectedFile();
                    song=myfile+"";
                   name=myfile.getName();
                    int len=name.length();
                    st=name.substring(len-4, len);
                    choose(); 
               Play(song);
              
                }  
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }          
    }//GEN-LAST:event_MlistMouseReleased

    public void Play(String song)
    {
        if(st.equals(".mp3"))
               {
                   flag=1;
                   sname.setText(name);
        try {
                  FIS=new FileInputStream(song);
                } catch (Exception ex) {
                    System.out.println(ex.getMessage());
                }
                if(fl==1&&f==0){
                    try {
                    FIS.skip(total_length-pouse);
                } catch (Exception ex) {
                    System.out.println(ex.getMessage());
                }fl=0;
                }
                else
                {
                 try {
            total_length=FIS.available();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
                f=0;}
                BIS=new BufferedInputStream(FIS);
                try {
                    player=new Player(BIS);
                } catch (Exception ex) {
                    System.out.println(ex.getMessage());
                }
        new Thread()
                {
                    public void run()
                    {
                        try
                        {
                            playb.setBackground(Color.BLUE);
                            player.play();
                           if(player.isComplete()){
                               f=1;
                               fp=0;
                               loop();
                           }
                           if(player.isComplete())
                               auto();
                        }   catch (Exception ex) {
                            System.out.println(ex.getMessage());
                        }
                    }
                }.start();
        }
         else
                   sname.setText("Please select an mp3 file!");
    }
    private void nextMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseReleased
        // TODO add your handling code here:
        fp=1;
        pause.setBackground(Color.LIGHT_GRAY);
        if(i==count-1)
            i=-1;
                     player.close();
                     i++;
                song= fil[i]+"";
                sname.setText(song);
                name=fil[i].getName();
                   Play(song);
    }//GEN-LAST:event_nextMouseReleased
    void  choose() throws FileNotFoundException
    {
         i=-1;
                 fil = ch.getCurrentDirectory().listFiles();
                 for(File file:fil)
                     count++;
                for ( File file : fil ) {
                     i++;
                     String st=file+"";
                if(st.equals(song)){
                    break;
                }
                 }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Jmusic_player is a free and open source music player which can play all mp3 files"
                + ".\nIt can work on any platform and Jmusic_player stands for Jaat music player"
                + " \n \n            Thanks."
                + "\n\n             Developer-Sunny Malik");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1ActionPerformed

    private void r1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r1MouseReleased
        // TODO add your handling code here:
        if(r1.isSelected()){
            b=true;
        }
        else
            b=false;
   
    }//GEN-LAST:event_r1MouseReleased
   void loop(){    
               if(b==true)
                   Play(song);
   }
    private void prevMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prevMouseReleased
        // TODO add your handling code here:
        pause.setBackground(Color.LIGHT_GRAY);
        if(i==0)
            i=count;
        player.close();
                     i--;
                song= fil[i]+"";
                sname.setText(song);
                name=fil[i].getName();
                   Play(song);
    }//GEN-LAST:event_prevMouseReleased

    private void r2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r2MouseReleased
        // TODO add your handling code here:
        if(r2.isSelected())
            c=true;
        else
            c=false;
    }//GEN-LAST:event_r2MouseReleased
    void auto()
    {
        if(c==true){
           if(i==count-1)
            i=-1;
                     player.close();
                     i++;
                     name=fil[i].getName();
                    int len=name.length();
                    st=name.substring(len-4, len);
                song= fil[i]+"";
                   Play(song);
        }
    }
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Mlist;
    private javax.swing.JLabel icon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton next;
    private javax.swing.JButton pause;
    private javax.swing.JButton playb;
    private javax.swing.JButton prev;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JLabel sname;
    // End of variables declaration//GEN-END:variables
}
